global:
  environment: "staging"
  image:
    repository: "morettimathieu"
  webapp:
    url: "http://hexagun-webapp.staging.svc.cluster.local"
    port: 8085

hexagun-webapp:
  nodePort: 30085
  image:
    repository: "morettimathieu/hexagun"
    tagLabel: 4-prod

hexagun-gateway:
  port: 8095
  nodePort: 30095
  image:
    repository: "morettimathieu/hexagun-gateway"
    tagLabel: 3-prod
