global:
  environment: "dev"
  image:
    repository: "morettimathieu"
  webapp:
    url: "http://hexagun-webapp.dev.svc"
    port: 8082

hexagun-webapp:
  nodePort: 30082
  image:
    repository: "morettimathieu/hexagun"
    tagLabel: 0.0.2-gffb5afc6

hexagun-gateway:
  port: 8092
  nodePort: 30092
  image:
    repository: "morettimathieu/hexagun-gateway"
    tagLabel: 0.0.1-g9cfca926
