global:
  environment: "staging"
  image:
    repository: "morettimathieu"
  webapp:
    url: "hexagun-webapp"
    port: 8085

hexagun-webapp:
  nodePort: 30085
  image:
    repository: "morettimathieu/hexagun"
    tagLabel: 12-prod

hexagun-gateway:
  port: 8095
  nodePort: 30095
  image:
    repository: "morettimathieu/hexagun-gateway"
    tagLabel: 5-prod
