global:
  environment: "prod"
  image:
    repository: "morettimathieu"
  webapp:
    url: "hexagun-webapp"
    port: 8088

hexagun-webapp:
  nodePort: 30088
  image:
    repository: "morettimathieu/hexagun"
    tagLabel: 4-prod

hexagun-gateway:
  port: 8098
  nodePort: 30098
  image:
    repository: "morettimathieu/hexagun-gateway"
    tagLabel: 5-prod
