global:
  environment: ""
  image:
    repository: "morettimathieu"
  webapp:
    url: "hexagun-webapp"
    port: 8081

hexagun-webapp:
  nodePort: 30081
  image:
    repository: "morettimathieu/hexagun"
    tagLabel: 13-prod

hexagun-gateway:
  port: 8091
  nodePort: 30091
  image:
    repository: "morettimathieu/hexagun-gateway"
    tagLabel: 5-prod