apiVersion: v1
kind: Service
metadata:
    name: hexagun-webapp
spec:
    selector:
        app: webapp
    
    ports:
    - name: http
      port: {{ default "8081" .Values.port }}
      nodePort: {{ default "30081" .Values.nodePort }}
    type: NodePort