apiVersion: v1
kind: ConfigMap
metadata:
    name: gateway-config-v1
data:
    config.yaml: |
        environment: {{ default "none" .Values.global.environment }}
        webapp.url: {{ default "" .Values.global.webapp.url }}
        webapp.port: {{ default "8081" .Values.global.webapp.port }}
        gateway.port: {{ default "8091" .Values.port }}