apiVersion: v1
kind: Service
metadata:
    name: hexagun-gateway
spec:
    selector:
        app: gateway
    
    ports:
    - name: http
      port: {{ default "8091" .Values.port }}
      nodePort: {{ default "30091" .Values.nodePort }}
    type: NodePort