apiVersion: v1
kind: ConfigMap
metadata:
    name: webapp-config-v2
data:
    config.yaml: |
        environment: {{ default "none" .Values.environment }}
        webapp.port: {{ default "8081" .Values.webapp.port }}