apiVersion: apps/v1
kind: Deployment
metadata:
    name: webapp
spec:
    selector:
        matchLabels:
            app: webapp
    replicas: 1
    template: # template for the pods
        metadata:
            labels:
                app: webapp
        spec:
            containers:
            - name: webapp
              image: morettimathieu/hexagun:4
              volumeMounts:
              - name: webapp-config-volume
                mountPath: /config
            volumes:
            - name: webapp-config-volume
              configMap: 
                name: webapp-config-v1