apiVersion: v1
kind: Service
metadata:
    name: hexagun-webapp
spec:
    selector:
        app: webapp
    
    ports:
    - name: http
      port: 8081
      nodePort: 30081
    type: NodePort